[package]
name = "prototype"
version = "0.0.1"
include = ["/src"]
edition = "2021"

[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
toolkits = { path = "./build/smithyprojections/software.amazon.smithy.rust.codegen.toolkits/source/rust-codegen" }
aws-smithy-process = { path = "./rust-runtime/aws-smithy-process" }
aws-smithy-json-rpc = { path = "./rust-runtime/aws-smithy-json-rpc" }
aws-smithy-server = { path = "./rust-runtime/aws-smithy-server" }
aws-smithy-core = { path = "./rust-runtime/aws-smithy-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "4.0.17"
yaml-rust = "0.4.5"
warp = "0.3"
futures = "0.3" # Used for extra utility functions over futures that tokio doesn't have

aws-credentials = { path = "./modules/credentials" }
aws-sam = { path = "./modules/sam" }
aws-cloudformation = { path = "./modules/cloudformation" }
# aws-cloudwatch = { path = "./modules/cloudwatch" }
aws-flow = { path = "./modules/flow" }
aws-ec2 = { path = "./modules/ec2" }
aws-core = { path = "./modules/core" }

# macros
macros = { path = "./src/macros" }
